### PR TITLE
[WIP] Add simple script that calls brittany on `**/*.hs`

### PR DESCRIPTION
**Pull request by fisx**
~~(currently choking on some modules).~~

### CODE REVIEW

**Comment by fisx** [comment]
This could work if we had plumbing that takes a backlist of modules that should not be processed.  Then we could use it everywhere except where it's not working, and occasionally go through the blacklist and see if we can get things to work after all.

**Comment by fisx** [comment]
https://github.com/lspitzner/brittany/issues/90#issuecomment-442973066

**Comment by fisx** [comment]
I think I made some progress with this today, but this package is making use of `QuasiQuotes` a lot, and those are not supported.

tasks:

- [ ] decide whether we want our code to look like https://github.com/wireapp/saml2-web-sso/pull/31/commits/cc082844ba9017b1f205763ff92a3c01a3b42f32 (keep in mind that this will give you freedom from having to think about code layout!)  @neongreen, @jschaul, @tiago-loureiro?
- [ ] eliminate `uri` quasiquotes and use `unsafePareURI` instead; eliminate or isolate `xml` quasiquotes.
- [ ] re-render (almost) everything).
- [ ] consider pushing the script upstream to brittany in some form.

**Comment by neongreen** [comment]
I took another look at Brittany's bug tracker recently and I still think
it's not ready to be actually used.

Things like https://github.com/lspitzner/brittany/issues/204 and
https://github.com/lspitzner/brittany/issues/174 are especially unpleasant,
though for different reasons.

It would be less scary if Brittany had a way to disable autoformatting per
file. I'm not sure if it does.

**Comment by neongreen** [comment]
This said, as long as it's for this library and not for wire-server as a
whole, I won't object to just going with it and seeing how it fares. Maybe
it's not as bad as I think.

**Comment by jschaul** [comment]
The "only run brittany on certain files but not all" part of the script looks fine. The question remains whether brittany is useful to be used to begin with.

Are there perhaps some configuration options in brittany that change the current formatting (were it to be used on the wire-server codebase) less radically?

e.g. one current function from galley:

```haskell
createOne2OneConversation :: U.UUID U.V4
                          -> U.UUID U.V4
                          -> Maybe (Range 1 256 Text)
                          -> Maybe TeamId
                          -> Galley Conversation
createOne2OneConversation a b name ti = do
    let conv = one2OneConvId a b
        a'   = Id (U.unpack a)
        b'   = Id (U.unpack b)
    now <- liftIO getCurrentTime
    retry x5 $ case ti of
        Nothing  -> write Cql.insertConv (params Quorum (conv, One2OneConv, a', privateOnly, privateRole, fromRange <$> name, Nothing, Nothing, Nothing))
        Just tid -> batch $ do
            setType BatchLogged
            setConsistency Quorum
            addPrepQuery Cql.insertConv (conv, One2OneConv, a', privateOnly, privateRole, fromRange <$> name, Just tid, Nothing, Nothing)
            addPrepQuery Cql.insertTeamConv (tid, conv, False)
    mems <- snd <$> addMembersUnchecked now conv a' (list1 a' [b'])
    return $ newConv conv One2OneConv a' (toList mems) [PrivateAccess] privateRole name ti Nothing Nothing
```
gets turned into 
```haskell
createOne2OneConversation
  :: U.UUID U.V4
  -> U.UUID U.V4
  -> Maybe (Range 1 256 Text)
  -> Maybe TeamId
  -> Galley Conversation
createOne2OneConversation a b name ti = do
  let conv = one2OneConvId a b
      a'   = Id (U.unpack a)
      b'   = Id (U.unpack b)
  now <- liftIO getCurrentTime
  retry x5 $ case ti of
    Nothing -> write
      Cql.insertConv
      (params
        Quorum
        ( conv
        , One2OneConv
        , a'
        , privateOnly
        , privateRole
        , fromRange <$> name
        , Nothing
        , Nothing
        , Nothing
        )
      )
    Just tid -> batch $ do
      setType BatchLogged
      setConsistency Quorum
      addPrepQuery
        Cql.insertConv
        ( conv
        , One2OneConv
        , a'
        , privateOnly
        , privateRole
        , fromRange <$> name
        , Just tid
        , Nothing
        , Nothing
        )
      addPrepQuery Cql.insertTeamConv (tid, conv, False)
  mems <- snd <$> addMembersUnchecked now conv a' (list1 a' [b'])
  return $ newConv conv
                   One2OneConv
                   a'
                   (toList mems)
                   [PrivateAccess]
                   privateRole
                   name
                   ti
                   Nothing
                   Nothing
```

The brittany result is (on my eyes) a lot less readable. 

There might be other cases where brittany makes the code worse to look at than before; would formatting a whole codebase (and then having to deal with some of the edge cases, and having some code that looks worse) be worth the time effort (and the small time gain of not having to format the code manually anymore)? Alternatively, couldn't only certain code blocks or imports be formatted through brittany or otherwise manually, rather than forcing formatting on the whole code base through a script?

**Comment by fisx** [comment]
CPP is unnecessary in surprisingly many cases, and could be avoided for reasons other than "i want to run brittany over every line of code": http://blog.haskell-exists.com/yuras/posts/stop-abusing-cpp-in-haskell.html

**Comment by fisx** [comment]
https://github.com/wireapp/saml2-web-sso/pull/59 won!

**Pull request closed without merging**
